### ISSUE TITLE
Friendly license

### ISSUE THREAD

**Issue by BigJoe01** [knielsen/lem-mariadb#3]
Hi, if possible publish better friendly license.

**Comment by knielsen** [comment]
The code is derived from LEM (https://github.com/esmil/lem) and lem-postgres (https://github.com/esmil/lem-postgres), which sets limits on the choice of License.

I have asked the LEM author if LGPL would be a possible alternative license to use.

**Comment by knielsen** [comment]
I got confirmation from the author of Lua Event Machine. I updated the README to say that the licence for lem-mariadb is LGPL.

**Comment by BigJoe01** [comment]
Thanks the information.
